using System;
using System.Collections.Generic;
using Newtonsoft.Json;

namespace BuildAI.AccIssueReturn.Core;

public enum IntegrationMode { IntegratedWithBuildAI, StandAlone }
public enum CoordinateQuality { ExactContext, ExactRoundTrip, RecoveredFromModelVersion, RecoveredFromKnownOffset, RecoveredFromElement, AmbiguousModel, InvalidCoordinates, MissingContext, Rejected }
public enum ImportState { NotSelected, PreviewReady, Warning, Blocked, Imported, Updated, Failed }
public enum CoordinateSpace { Unverified, ViewerLocal, ViewerWorld, Model, RevitLinkInternalFeet, RevitHostInternalFeet }
public enum CoordinateContract { Unverified, ViewerLocalFeetPlusGlobalOffset, ViewerLocalModelUnits }
public enum CameraPointContract { Unverified, RevitLinkInternalFeet }
public enum ContractConfidence { Confirmed, Strong, Ambiguous, Rejected }
public sealed class CoordinateContractDecision { public CoordinateContract Contract { get; set; } public ContractConfidence Confidence { get; set; } public List<string> Evidence { get; set; }=new(); public List<string> Conflicts { get; set; }=new(); public string Source { get; set; }=""; public bool IsAutomaticImportAllowed { get; set; } }
public sealed class AccHub { public string Id { get; set; } = ""; public string Name { get; set; } = ""; }
public sealed class AccProject { public string HubId { get; set; } = ""; public string Id { get; set; } = ""; public string Name { get; set; } = ""; public string Region { get; set; } = ""; }
public enum AccModelSource { ProjectCatalog, IssueLinkedDocument, IssueViewerState, IssueObjectSet, ResolvedDerivative }
public enum VersionResolutionStatus { Unknown, Resolving, Resolved, Historical, LatestResolved, Ambiguous, Unavailable, InvalidCandidate, NoAccess }
public enum AccModelResolutionStatus { Resolved, PartiallyResolved, Unresolved, Ambiguous }
public sealed class AccModelIdentity { public string ProjectId { get; set; }=""; public string Region { get; set; }=""; public string FolderId { get; set; }=""; public string ItemId { get; set; }=""; public string LineageUrn { get; set; }=""; public string VersionId { get; set; }=""; public int? VersionNumber { get; set; } public string VersionUrn { get; set; }=""; public string DerivativeUrn { get; set; }=""; public string SeedUrn { get; set; }=""; public string ViewableGuid { get; set; }=""; public string DisplayName { get; set; }=""; public string FolderPath { get; set; }=""; public DateTime? VersionCreatedAt { get; set; } public VersionResolutionStatus VersionStatus { get; set; }=VersionResolutionStatus.Unknown; public string VersionNumberSource { get; set; }=""; public string LatestStatusSource { get; set; }=""; public string VersionUrnSource { get; set; }=""; public AccModelSource Source { get; set; } public AccModelResolutionStatus ResolutionStatus { get; set; } }
public sealed class AccModel { public string ProjectId { get; set; } = ""; public string Id { get; set; } = ""; public string Name { get; set; } = ""; public string ItemUrn { get; set; } = ""; public string LineageUrn { get; set; } = ""; public string FolderId { get; set; } = ""; public string VersionId { get; set; } = ""; public string VersionUrn { get; set; } = ""; public string DerivativeUrn { get; set; } = ""; public int? VersionNumber { get; set; } public DateTime? VersionDateUtc { get; set; } public string ViewableGuid { get; set; } = ""; public string SeedUrn { get; set; } = ""; public string Region { get; set; } = ""; public string FolderPath { get; set; } = ""; public bool IsLatest { get; set; } public VersionResolutionStatus VersionStatus { get; set; }=VersionResolutionStatus.Unknown; public string VersionNumberSource { get; set; }=""; public string LatestStatusSource { get; set; }=""; public string VersionUrnSource { get; set; }=""; public string ResolutionEvidence { get; set; }=""; public int RelatedIssueCount { get; set; } public AccModelSource Source { get; set; }=AccModelSource.ProjectCatalog; public AccModelResolutionStatus ResolutionStatus { get; set; }=AccModelResolutionStatus.Resolved; public string DisplayLabel=>Name+" | "+(VersionNumber.HasValue?("V"+VersionNumber.Value+(IsLatest?" (latest)":"")):VersionStatus==VersionResolutionStatus.Ambiguous?"Version ambiguous":VersionStatus==VersionResolutionStatus.Resolving?"Resolving version…":VersionStatus==VersionResolutionStatus.InvalidCandidate?"Invalid version reference":"Version unknown")+(RelatedIssueCount>0?" | Issues: "+RelatedIssueCount:"")+(Source==AccModelSource.IssueLinkedDocument?" | Referenced by Issues":""); }
public sealed class AccCamera { public double[] Eye { get; set; } = new double[3]; public double[] Target { get; set; } = new double[3]; public double[] Up { get; set; } = new double[3]; public double FieldOfView { get; set; } public bool IsPerspective { get; set; } = true; }
public sealed class AccObjectRef { public string ModelUrn { get; set; } = ""; public string ExternalId { get; set; } = ""; public List<string> ExternalIds { get; set; } = new(); public int? DbId { get; set; } public List<int> DbIds { get; set; } = new(); public string RevitUniqueId { get; set; } = ""; public string LinkDocumentUniqueId { get; set; } = ""; public string LinkInstanceUniqueId { get; set; } = ""; public CompositeExternalId? Composite { get; set; } public string MatchedRevitUniqueId { get; set; } = ""; public string MatchedDocument { get; set; } = ""; public bool MappingAmbiguous { get; set; } }
public sealed class Matrix4 { public double[] M { get; set; } = IdentityArray(); public static Matrix4 Identity() => new(); public static double[] IdentityArray()=>new[]{1d,0,0,0,0,1d,0,0,0,0,1d,0,0,0,0,1d}; }
public sealed class IssueCoordinateContext
{
    public string ModelUrn { get; set; } = ""; public string VersionUrn { get; set; } = ""; public string ViewableGuid { get; set; } = ""; public string ViewableUrn { get; set; } = ""; public string ModelPropertiesGuid { get; set; } = "";
    public string SourceUnits { get; set; } = ""; public UnitParseStatus UnitStatus { get; set; }=UnitParseStatus.Missing; public LengthUnit? Unit { get; set; } public double? MetresPerUnit { get; set; } public LengthUnit? ViewerCoordinateUnit { get; set; } public LengthUnit? ModelDisplayUnit { get; set; } public LengthUnit? PropertyValueUnit { get; set; } public LengthUnit RevitInternalUnit { get; set; }=LengthUnit.Foot; public string Region { get; set; } = "";
    public double[] GlobalOffset { get; set; } = new[]{double.NaN,double.NaN,double.NaN}; public Matrix4 PlacementTransform { get; set; } = Matrix4.Identity(); public Matrix4 LinkToHost { get; set; } = Matrix4.Identity();
    public CoordinateContract Contract { get; set; } public CoordinateSpace PushpinSpace { get; set; } public CoordinateSpace GlobalOffsetSpace { get; set; } public CameraPointContract CameraContract { get; set; }
    public CoordinateTransformDirection PlacementDirection { get; set; } public MatrixSourceFormat MatrixFormat { get; set; }
    public string UnitsSource { get; set; } = ""; public string GlobalOffsetSource { get; set; } = ""; public string PlacementTransformSource { get; set; } = ""; public string ViewableSource { get; set; } = "";
    public CoordinateContractDecision ContractDecision { get; set; }=new(); public string TransformSource { get; set; } = ""; public string ModelDate { get; set; } = ""; public string IncompleteReason { get; set; } = "";
    public List<string> ContextSources { get; set; } = new();
    public bool HasKnownUnits=>UnitStatus==UnitParseStatus.Known&&Unit.HasValue&&MetresPerUnit.HasValue;
    public bool IsComplete => !string.IsNullOrWhiteSpace(ModelUrn) && !string.IsNullOrWhiteSpace(VersionUrn) && !string.IsNullOrWhiteSpace(ViewableGuid) && Contract!=CoordinateContract.Unverified && MatrixMath.IsFinite(GlobalOffset) && MatrixMath.IsInvertible(LinkToHost) && (Contract==CoordinateContract.ViewerLocalFeetPlusGlobalOffset ? ViewerCoordinateUnit==LengthUnit.Foot : HasKnownUnits&&MatrixMath.IsInvertible(PlacementTransform));
}
public sealed class AccIssue
{
    public string HubId { get; set; } = ""; public string ProjectId { get; set; } = ""; public string ContainerId { get; set; } = ""; public string Id { get; set; } = ""; public int? DisplayId { get; set; } public string Title { get; set; } = ""; public string Description { get; set; } = ""; public string Status { get; set; } = ""; public string Type { get; set; } = ""; public string AssignedUserId { get; set; } = ""; public string AssignedUserName { get; set; } = ""; public string Author { get; set; } = ""; public DateTime? CreatedAtUtc { get; set; } public DateTime? DueDateUtc { get; set; } public string Url { get; set; } = ""; public string ScreenshotUrl { get; set; } = "";
    public string ModelUrn { get; set; } = ""; public BuildAiRevitIssueRecord? BuildAiRecord { get; set; } public BuildAiMappingStatus BuildAiMappingStatus { get; set; }=BuildAiMappingStatus.NotRequested; public string RevitMappingSource { get; set; }=""; public string LineageUrn { get; set; } = ""; public string DerivativeUrn { get; set; } = ""; public string VersionUrn { get; set; } = ""; public string SeedUrn { get; set; } = ""; public string ViewableGuid { get; set; } = ""; public double[]? PushpinPosition { get; set; } public AccCamera? Camera { get; set; } public List<AccObjectRef> ObjectSet { get; set; } = new(); public string RawJson { get; set; } = ""; public IssueCoordinateContext? Context { get; set; } public ImportState ImportState { get; set; } public CoordinateQuality CoordinateQuality { get; set; } public string Warning { get; set; } = ""; public string MatchSummary { get; set; } = "";
    [JsonIgnore] public bool HasPushpin => PushpinPosition is { Length: 3 }; [JsonIgnore] public bool HasObjectSet => ObjectSet.Count > 0;
}
public sealed class CoordinateResult
{
    public CoordinateQuality Quality { get; set; } public double[] SourcePoint { get; set; } = new double[3]; public double[] RevitPointFeet { get; set; } = new double[3]; public double[] RoundTripPoint { get; set; } = new double[3]; public double RoundTripErrorMm { get; set; } public string MatchedLink { get; set; } = ""; public string MatchedRevitUniqueId { get; set; } = ""; public string MatchedDocument { get; set; } = ""; public string Warning { get; set; } = ""; public double CameraTargetDeltaFt { get; set; } public bool CameraTargetMatchesPushpin { get; set; } public List<string> Diagnostics { get; set; } = new();
    public bool MatrixRoundTripPassed { get; set; } public bool ScaleSanityPassed { get; set; } public bool ModelBoundsPassed { get; set; } public bool GeometryProximityPassed { get; set; } public bool ExternalIdMatched { get; set; } public bool ExpectedFixturePassed { get; set; } public bool CoordinateValidated { get; set; }
    public bool IsImportable => CoordinateValidated && MatrixMath.IsFinite(RevitPointFeet);
}
public sealed class CoordinateBounds { public double[] Min { get; set; }=new double[3]; public double[] Max { get; set; }=new double[3]; }
public sealed class CoordinateValidationEvidence { public CoordinateBounds? ModelBoundsFeet { get; set; } public CoordinateBounds? GeometryBoundsFeet { get; set; } public IReadOnlyList<CoordinateBounds>? GeometryElementBoundsFeet { get; set; } public bool ExternalIdMatched { get; set; } public double[]? ExpectedRevitPointFeet { get; set; } public double ExpectedToleranceMm { get; set; }=1; }
public readonly struct CoordinateContextCacheKey : IEquatable<CoordinateContextCacheKey>
{
    public CoordinateContextCacheKey(string projectId,string region,string versionUrn,string viewableGuid){ProjectId=projectId??"";Region=region??"";VersionUrn=versionUrn??"";ViewableGuid=viewableGuid??"";}
    public string ProjectId { get; } public string Region { get; } public string VersionUrn { get; } public string ViewableGuid { get; }
    public bool Equals(CoordinateContextCacheKey other)=>StringComparer.OrdinalIgnoreCase.Equals(ProjectId,other.ProjectId)&&StringComparer.OrdinalIgnoreCase.Equals(Region,other.Region)&&StringComparer.OrdinalIgnoreCase.Equals(VersionUrn,other.VersionUrn)&&StringComparer.OrdinalIgnoreCase.Equals(ViewableGuid,other.ViewableGuid);
    public override bool Equals(object? obj)=>obj is CoordinateContextCacheKey other&&Equals(other);
    public override int GetHashCode(){unchecked{var h=StringComparer.OrdinalIgnoreCase.GetHashCode(ProjectId);h=h*397^StringComparer.OrdinalIgnoreCase.GetHashCode(Region);h=h*397^StringComparer.OrdinalIgnoreCase.GetHashCode(VersionUrn);h=h*397^StringComparer.OrdinalIgnoreCase.GetHashCode(ViewableGuid);return h;}}
    public override string ToString()=>ProjectId+"|"+Region+"|"+VersionUrn+"|"+ViewableGuid;
}
public sealed class PreviewRow { public AccIssue Issue { get; set; } = new(); public CoordinateResult Coordinates { get; set; } = new(); public string ModelVersionSource { get; set; }=""; public string ElementMappingSource { get; set; }=""; public bool AccExternalIdMatched { get; set; } public bool BuildAiExactElementMatched { get; set; } public string RevitDocument { get; set; } = ""; public string RevitLink { get; set; } = ""; public string RevitLinkInstanceUniqueId { get; set; } = ""; public List<string> Elements { get; set; } = new(); public List<string> BlockingReasons { get; set; } = new(); public bool ExistingMarker { get; set; } public bool CanPreview => true; public bool CanImport => Coordinates.IsImportable; public string CoordinateSource => Coordinates.Quality==CoordinateQuality.RecoveredFromElement?"Recovered from element geometry":"ACC viewer state"; public string CoordinateValidation => Coordinates.CoordinateValidated?"Validated":"Unvalidated"; public string BlockingReasonText => string.Join("; ",BlockingReasons); public string Action => ExistingMarker ? "Update" : "Create"; }
public sealed class ImportSummary { public int ModelsSelected, IssuesLoaded, IssuesFiltered, IssuesSelected, PreviewValid, PreviewWarning, PreviewRejected, MarkersCreated, MarkersUpdated, MarkersSkipped, ExactCoordinates, RecoveredCoordinates, Failed, ViewApplied; }
public interface IAccAuthProvider { IntegrationMode Mode { get; } string BackendUrl { get; } System.Threading.Tasks.Task<string> GetAccessTokenAsync(System.Threading.CancellationToken ct); }
public interface IAccIssueClient { System.Threading.Tasks.Task<IReadOnlyList<AccHub>> GetHubsAsync(System.Threading.CancellationToken ct); System.Threading.Tasks.Task<IReadOnlyList<AccProject>> GetProjectsAsync(string hubId,System.Threading.CancellationToken ct); System.Threading.Tasks.Task<IReadOnlyList<AccModel>> GetModelsAsync(string projectId,System.Threading.CancellationToken ct); System.Threading.Tasks.Task<IReadOnlyList<AccIssue>> GetIssuesAsync(AccProject project,IReadOnlyCollection<AccModel> models,System.Threading.CancellationToken ct,IProgress<string>? progress=null); System.Threading.Tasks.Task<IssueCoordinateContext> GetContextAsync(AccIssue issue,AccModel model,System.Threading.CancellationToken ct); }





