using System; using System.Collections.Generic; using System.IO; using System.Net.Http; using System.Net.Http.Headers; using System.Text; using System.Threading; using System.Threading.Tasks; using Newtonsoft.Json; using Newtonsoft.Json.Linq; using Plugin5.ClashFormaIntegration.Models;
namespace Plugin5.ClashFormaIntegration.Publishing {
 public sealed class ApsPublisher {
  const string Api="https://developer.api.autodesk.com";
  public async Task<ViewerPublication> PublishAsync(string file,Plugin5Settings s,IProgress<string> progress,CancellationToken ct){
   if(string.IsNullOrWhiteSpace(s.ApsClientId)||string.IsNullOrWhiteSpace(s.ApsClientSecret))throw new InvalidOperationException("APS Client ID/Secret are not configured.");
   using(var h=new HttpClient()){h.Timeout=TimeSpan.FromMinutes(30);var token=await Token(h,s,ct);h.DefaultRequestHeaders.Authorization=new AuthenticationHeaderValue("Bearer",token);var bucket=NormalizeBucket(s.ApsBucketKey,s.ApsClientId);progress?.Report("Sozdanie APS bucket...");await EnsureBucket(h,bucket,ct);
    var objectKey=DateTime.UtcNow.ToString("yyyyMMddHHmmss")+"_"+Path.GetFileName(file);progress?.Report("Zagruzka modeli v APS OSS...");await UploadSigned(h,bucket,objectKey,file,ct);
    var objectId=$"urn:adsk.objects:os.object:{bucket}/{objectKey}";var urn=Convert.ToBase64String(Encoding.UTF8.GetBytes(objectId)).TrimEnd('=').Replace('+','-').Replace('/','_');progress?.Report("Zapusk perevoda SVF2...");
    var job=new{input=new{urn},output=new{formats=new[]{new{type="svf2",views=new[]{"2d","3d"}}}}};var jr=await h.PostAsync(Api+"/modelderivative/v2/designdata/job",new StringContent(JsonConvert.SerializeObject(job),Encoding.UTF8,"application/json"),ct);jr.EnsureSuccessStatusCode();
    string status="inprogress";for(var i=0;i<180;i++){ct.ThrowIfCancellationRequested();await Task.Delay(5000,ct);var mr=await h.GetAsync(Api+$"/modelderivative/v2/designdata/{urn}/manifest",ct);if(!mr.IsSuccessStatusCode)continue;var m=JObject.Parse(await mr.Content.ReadAsStringAsync());status=(string)m["status"]??"inprogress";var pr=(string)m["progress"]??"";progress?.Report("SVF2: "+pr);if(status=="success"||status=="failed"||status=="timeout")break;}if(status!="success")throw new InvalidOperationException("APS translation finished with status: "+status);
    return new ViewerPublication{PublicationId=Guid.NewGuid().ToString("N"),ProjectId=s.BuildAiProjectId,SourceFileName=Path.GetFileName(file),ApsUrn=urn,Status="ready",ViewerTokenEndpoint=s.BuildAiBaseUrl.TrimEnd('/')+"/api/aps/viewer-token"};
   }}
  static async Task<string> Token(HttpClient h,Plugin5Settings s,CancellationToken ct){var basic=Convert.ToBase64String(Encoding.UTF8.GetBytes(s.ApsClientId+":"+s.ApsClientSecret));using(var q=new HttpRequestMessage(HttpMethod.Post,Api+"/authentication/v2/token")){q.Headers.Authorization=new AuthenticationHeaderValue("Basic",basic);q.Content=new FormUrlEncodedContent(new[]{new KeyValuePair<string,string>("grant_type","client_credentials"),new KeyValuePair<string,string>("scope","data:read data:write data:create bucket:create bucket:read")});var r=await h.SendAsync(q,ct);r.EnsureSuccessStatusCode();return (string)JObject.Parse(await r.Content.ReadAsStringAsync())["access_token"];}}
  static string NormalizeBucket(string x,string id){var s=string.IsNullOrWhiteSpace(x)?("buildai-"+id):x;s=s.ToLowerInvariant();var b=new StringBuilder();foreach(var c in s)if(char.IsLetterOrDigit(c)||c=='-'||c=='_'||c=='.')b.Append(c);return b.ToString().Substring(0,Math.Min(128,b.Length));}
  static async Task EnsureBucket(HttpClient h,string bucket,CancellationToken ct){var body=new{bucketKey=bucket,policyKey="persistent"};var r=await h.PostAsync(Api+"/oss/v2/buckets",new StringContent(JsonConvert.SerializeObject(body),Encoding.UTF8,"application/json"),ct);if(!r.IsSuccessStatusCode&&r.StatusCode!=System.Net.HttpStatusCode.Conflict)r.EnsureSuccessStatusCode();}
  static async Task UploadSigned(HttpClient h,string bucket,string key,string file,CancellationToken ct){var u=Api+$"/oss/v2/buckets/{Uri.EscapeDataString(bucket)}/objects/{Uri.EscapeDataString(key)}/signeds3upload?parts=1";var r=await h.GetAsync(u,ct);r.EnsureSuccessStatusCode();var j=JObject.Parse(await r.Content.ReadAsStringAsync());var url=(string)j["urls"]?[0];var uploadKey=(string)j["uploadKey"];using(var raw=new HttpClient())using(var fs=File.OpenRead(file)){var put=await raw.PutAsync(url,new StreamContent(fs),ct);put.EnsureSuccessStatusCode();}var fin=new{uploadKey};var fr=await h.PostAsync(Api+$"/oss/v2/buckets/{Uri.EscapeDataString(bucket)}/objects/{Uri.EscapeDataString(key)}/signeds3upload",new StringContent(JsonConvert.SerializeObject(fin),Encoding.UTF8,"application/json"),ct);fr.EnsureSuccessStatusCode();}
 }
}
